export const engnovateReadingAnswers: Record<string, Record<number, string | string[]>> = {
    "cambridge-10|test-1": {
        "1": "FALSE",
        "2": "TRUE",
        "3": "NOT GIVEN",
        "4": "NOT GIVEN",
        "5": "TRUE",
        "6": "pavilions",
        "7": "drought",
        "8": "tourists",
        "9": "Earthquake",
        "10": "Four sides",
        "11": "Tank",
        "12": "verandas",
        "13": "underwater",
        "14": "viii",
        "15": "iii",
        "16": "xi",
        "17": "i",
        "18": "v",
        "19": "x",
        "20": "ii",
        "21": "iv",
        "22": "TRUE",
        "23": "FALSE",
        "24": "NOT GIVEN",
        "25": "NOT GIVEN",
        "26": "FALSE",
        "27": "C",
        "28": "A",
        "29": "D",
        "30": "B",
        "31": "G",
        "32": "E",
        "33": "A",
        "34": "F",
        "35": "B",
        "36": "NO",
        "37": "YES",
        "38": "NOT GIVEN",
        "39": "NOT GIVEN",
        "40": "NO"
    },
    "cambridge-10|test-2": {
        "1": "iv",
        "2": "viii",
        "3": "vii",
        "4": "i",
        "5": "vi",
        "6": "ix",
        "7": "ii",
        "8": "NOT GIVEN",
        "9": "TRUE",
        "10": "FALSE",
        "11": "FALSE",
        "12": "NOT GIVEN",
        "13": "TRUE",
        "14": "A",
        "15": "D",
        "16": "F",
        "17": "D",
        "18": "B",
        "19": "D",
        "20": "E",
        "21": "A",
        "22": "C",
        "23": "books and activities",
        "24": "internal regulation",
        "25": "emotional awareness",
        "26": "spoon-feeding",
        "27": "B",
        "28": "H",
        "29": "L",
        "30": "G",
        "31": "D",
        "32": "C",
        "33": "D",
        "34": "A",
        "35": "D",
        "36": "NOT GIVEN",
        "37": "NO",
        "38": "YES",
        "39": "NOT GIVEN",
        "40": "NO"
    },
    "cambridge-10|test-3": {
        "1": "ii",
        "2": "i",
        "3": "v",
        "4": "vii",
        "5": "TRUE",
        "6": "NOT GIVEN",
        "7": "NOT GIVEN",
        "8": "TRUE",
        "9": "NOT GIVEN",
        "10": "FALSE",
        "11": "source of income",
        "12": "employer",
        "13": "domestic tourism",
        "14": "C",
        "15": "B",
        "16": "H",
        "17": "B",
        "18": "E",
        "19": "sun",
        "20": "upper",
        "21": "dry",
        "22": "north",
        "23": "FALSE",
        "24": "TRUE",
        "25": "NOT GIVEN",
        "26": "B",
        "27": "B",
        "28": "F",
        "29": "I",
        "30": "G",
        "31": "D",
        "32": "C",
        "33": "A",
        "34": "D",
        "35": "C",
        "36": "NO",
        "37": "YES",
        "38": "NOT GIVEN",
        "39": "YES",
        "40": "NOT GIVEN"
    },
    "cambridge-10|test-4": {
        "1": "spread",
        "2": "10",
        "3": "below",
        "4": "fuel",
        "5": "seasons",
        "6": "homes",
        "7": "TRUE",
        "8": "FALSE",
        "9": "TRUE",
        "10": "TRUE",
        "11": "NOT GIVEN",
        "12": "FALSE",
        "13": "FALSE",
        "14": "transformation",
        "15": "young age",
        "16": "optimism",
        "17": "skills",
        "18": "negative emotions",
        "19": "E",
        "20": "C",
        "21": "G",
        "22": "A",
        "23": "E",
        "24": "C",
        "25": "G",
        "26": "H",
        "27": "C",
        "28": "D",
        "29": "C",
        "30": "B",
        "31": "A",
        "32": "F",
        "33": "G",
        "34": "A",
        "35": "B",
        "36": "D",
        "37": "NOT GIVEN",
        "38": "YES",
        "39": "NO",
        "40": "YES"
    },
    "cambridge-11|test-1": {
        "1": "tomatoes",
        "2": ["urban centres", "centers"],
        "3": "energy",
        "4": "fossil fuel",
        "5": "artificial",
        "6": "(stacked) trays",
        "7": "(urban) rooftops",
        "8": "NOT GIVEN",
        "9": "TRUE",
        "10": "FALSE",
        "11": "TRUE",
        "12": "FALSE",
        "13": "TRUE",
        "14": "FALSE",
        "15": "NOT GIVEN",
        "16": "TRUE",
        "17": "NOT GIVEN",
        "18": "FALSE",
        "19": "TRUE",
        "20": "gates",
        "21": "clamp",
        "22": "axle",
        "23": "cogs",
        "24": "aqueduct",
        "25": "wall",
        "26": "locks",
        "27": "D",
        "28": "B",
        "29": "A",
        "30": "sunshade",
        "31": "iron",
        "32": "algae",
        "33": "clouds",
        "34": "cables",
        "35": "snow",
        "36": "rivers",
        "37": "B",
        "38": "D",
        "39": "C",
        "40": "A",
    },
    "cambridge-11|test-2": {
        "1": "TRUE",
        "2": "NOT GIVEN",
        "3": "TRUE",
        "4": "FALSE",
        "5": "C",
        "6": "B",
        "7": "G",
        "8": "A",
        "9": "(lifting) frame",
        "10": "hydraulic jacks",
        "11": "stabbing guides",
        "12": "(lifting) cradle",
        "13": "air bags",
        "14": "ii",
        "15": "ix",
        "16": "viii",
        "17": "i",
        "18": "iv",
        "19": "vii",
        "20": "vi",
        "21": "farming",
        "22": "canoes",
        "23": "birds",
        "24": "wood",
        "25": "B",
        "26": "C",
        "27": "C",
        "28": "D",
        "29": "B",
        "30": "A",
        "31": "C",
        "32": "B",
        "33": "H",
        "34": "NOT GIVEN",
        "35": "YES",
        "36": "NO",
        "37": "NO",
        "38": "YES",
        "39": "NOT GIVEN",
        "40": "A",
    },
    "cambridge-11|test-3": {
        "1": "tea",
        "2": "reel",
        "3": "women",
        "4": "royalty",
        "5": "currency",
        "6": "paper",
        "7": "wool",
        "8": "monks",
        "9": "nylon",
        "10": "FALSE",
        "11": "TRUE",
        "12": "FALSE",
        "13": "NOT GIVEN",
        "14": "FALSE",
        "15": "TRUE",
        "16": "NOT GIVEN",
        "17": "TRUE",
        "18": "FALSE",
        "19": "G",
        "20": "C",
        "21": "A",
        "22": "E",
        "23": "speed",
        "24": "plains",
        "25": "bottlenecks",
        "26": ["corridor", "passageway"],
        "27": "D",
        "28": "B",
        "29": "G",
        "30": "C",
        "31": "B",
        "32": "E",
        "33": "A",
        "34": "F",
        "35": "beginner",
        "36": "arithmetic",
        "37": "intuitive",
        "38": "scientists",
        "39": "experiments",
        "40": "theorems",
    },
    "cambridge-11|test-4": {
        "1": "FALSE",
        "2": "NOT GIVEN",
        "3": "NOT GIVEN",
        "4": "TRUE",
        "5": "A",
        "6": "C",
        "7": "A",
        "8": "B",
        "9": "B",
        "10": "D",
        "11": "B",
        "12": "E",
        "13": "F",
        "14": "B",
        "15": "A",
        "16": "B",
        "17": "D",
        "18": "C",
        "19": "TRUE",
        "20": "TRUE",
        "21": "NOT GIVEN",
        "22": "TRUE",
        "23": "FALSE",
        "24": "C",
        "25": "A",
        "26": "E",
        "27": "vi",
        "28": "iv",
        "29": "ii",
        "30": "vii",
        "31": "i",
        "32": "v",
        "33": "E",
        "34": "G",
        "35": "B",
        "36": "F",
        "37": "NO",
        "38": "YES",
        "39": "NOT GIVEN",
        "40": "YES",
    },
    "cambridge-12|test-1": {
        "1": "NOT GIVEN",
        "2": "FALSE",
        "3": "FALSE",
        "4": "TRUE",
        "5": "TRUE",
        "6": "taste",
        "7": "cheaper",
        "8": "convenient",
        "9": "image",
        "10": "sustainable",
        "11": "recycled",
        "12": "biodiversity",
        "13": "desertification",
        "14": "antiques",
        "15": "triumph",
        "16": "information",
        "17": ["contact", "meetings"],
        "18": ["hunt", "desire"],
        "19": ["aimless", "empty"],
        "20": "educational",
        "21": "Trainspotting",
        "22": "NOT GIVEN",
        "23": "FALSE",
        "24": "NOT GIVEN",
        "25": "TRUE",
        "26": "TRUE",
        "27": "vi",
        "28": "viii",
        "29": "ii",
        "30": "iv",
        "31": "iii",
        "32": "vii",
        "33": "fire science",
        "34": "investigators",
        "35": "evidence",
        "36": "prosecution",
        "37": "NOT GIVEN",
        "38": "YES",
        "39": "NO",
        "40": "NO",
    },
    "cambridge-12|test-2": {
        "1": "A",
        "2": "B",
        "3": "H",
        "4": "D",
        "5": "B",
        "6": "C",
        "7": "G",
        "8": "B",
        "9": "A",
        "10": "D",
        "11": "E",
        "12": "C",
        "13": "D",
        "14": "iv",
        "15": "vi",
        "16": "viii",
        "17": "v",
        "18": "i",
        "19": "vii",
        "20": "iii",
        "21": "TRUE",
        "22": "FALSE",
        "23": "FALSE",
        "24": "NOT GIVEN",
        "25": "rubber",
        "26": "farmer",
        "27": "eye movements",
        "28": "language co-activation",
        "29": "Stroop Task",
        "30": "conflict management",
        "31": "cognitive control",
        "32": "YES",
        "33": "NOT GIVEN",
        "34": "NO",
        "35": "NO",
        "36": "NOT GIVEN",
        "37": "D",
        "38": "G",
        "39": "B",
        "40": "C",
    },
    "cambridge-12|test-3": {
        "1": "v",
        "2": "iii",
        "3": "viii",
        "4": "i",
        "5": "iv",
        "6": "vi",
        "7": "ii",
        "8": "pirates",
        "9": "food",
        "10": "oil",
        "11": "settlers",
        "12": "species",
        "13": "eggs",
        "14": "D",
        "15": "C",
        "16": "F",
        "17": "G",
        "18": "D",
        "19": "B",
        "20": "vaccinations",
        "21": "antibiotics",
        "22": "mosquito(e)s",
        "23": "factories",
        "24": "forests",
        "25": "Polio",
        "26": "mountain",
        "27": "dopamine",
        "28": "pleasure",
        "29": "caudate",
        "30": "anticipatory phase",
        "31": "food",
        "32": "B",
        "33": "C",
        "34": "A",
        "35": "B",
        "36": "D",
        "37": "F",
        "38": "B",
        "39": "E",
        "40": "C",
    },
    "cambridge-12|test-4": {
        "1": "obsidian",
        "2": "spears",
        "3": "beads",
        "4": "impurities",
        "5": "Romans",
        "6": "lead",
        "7": "clouding",
        "8": "taxes",
        "9": "TRUE",
        "10": "FALSE",
        "11": "NOT GIVEN",
        "12": "TRUE",
        "13": "FALSE",
        "14": "D",
        "15": "A",
        "16": "C",
        "17": "A",
        "18": "C",
        "19": "E",
        "20": "D",
        "21": "F",
        "22": "A",
        "23": "NO",
        "24": "NOT GIVEN",
        "25": "YES",
        "26": "YES",
        "27": "iv",
        "28": "ii",
        "29": "vi",
        "30": "viii",
        "31": "vii",
        "32": "i",
        "33": "iii",
        "34": "YES",
        "35": "NOT GIVEN",
        "36": "NO",
        "37": "NO",
        "38": "information",
        "39": "financial",
        "40": ["shareholders", "investors"],
    },
    "cambridge-13|test-1": {
        "1": "update",
        "2": "environment",
        "3": "captain",
        "4": "films",
        "5": "season",
        "6": "accommodation",
        "7": "blog",
        "8": "FALSE",
        "9": "NOT GIVEN",
        "10": "FALSE",
        "11": "TRUE",
        "12": "NOT GIVEN",
        "13": "TRUE",
        "14": "iv",
        "15": "vi",
        "16": "i",
        "17": "v",
        "18": "viii",
        "19": "iii",
        "20": "E",
        "21": "B",
        "22": "D",
        "23": "A",
        "24": "focus",
        "25": "pleasure",
        "26": "curiosity",
        "27": "B",
        "28": "C",
        "29": "C",
        "30": "D",
        "31": "A",
        "32": "D",
        "33": "A",
        "34": "E",
        "35": "C",
        "36": "G",
        "37": "B",
        "38": "YES",
        "39": "NOT GIVEN",
        "40": "NO",
    },
    "cambridge-13|test-2": {
        "1": "oils",
        "2": "friendship",
        "3": "funerals",
        "4": "wealth",
        "5": "indigestion",
        "6": "India",
        "7": "camels",
        "8": "Alexandria",
        "9": "Venice",
        "10": "TRUE",
        "11": "FALSE",
        "12": "NOT GIVEN",
        "13": "FALSE",
        "14": "B",
        "15": "F",
        "16": "B",
        "17": "E",
        "18": "A",
        "19": "B",
        "20": "C",
        "21": "animals",
        "22": "childbirth",
        "23": "placebo",
        "24": "game",
        "25": "strangers",
        "26": "names",
        "27": "D",
        "28": "C",
        "29": "A",
        "30": "D",
        "31": "D",
        "32": "D",
        "33": "C",
        "34": "B",
        "35": "A",
        "36": "C",
        "37": "A",
        "38": "B",
        "39": "C",
        "40": "D",
    },
    "cambridge-13|test-3": {
        "1": "furniture",
        "2": "sugar",
        "3": "ropes",
        "4": "charcoal",
        "5": "bowls",
        "6": "hormones",
        "7": "cosmetics",
        "8": "dynamite",
        "9": "FALSE",
        "10": "FALSE",
        "11": "NOT GIVEN",
        "12": "TRUE",
        "13": "NOT GIVEN",
        "14": "B",
        "15": "C",
        "16": "A",
        "17": "B",
        "18": "recording devices",
        "19": ["fathers", "dads"],
        "20": "bridge hypothesis",
        "21": "repertoire",
        "22": "(audio-recording) vests",
        "23": "vocabulary",
        "24": "F",
        "25": "A",
        "26": "E",
        "27": "C",
        "28": "H",
        "29": "A",
        "30": "B",
        "31": "D",
        "32": "shells",
        "33": "lake",
        "34": "rainfall",
        "35": "grains",
        "36": "pottery",
        "37": "B",
        "38": "A",
        "39": "D",
        "40": "A",
    },
    "cambridge-13|test-4": {
        "1": "FALSE",
        "2": "FALSE",
        "3": "TRUE",
        "4": "TRUE",
        "5": "FALSE",
        "6": "TRUE",
        "7": "NOT GIVEN",
        "8": "TRUE",
        "9": "wool",
        "10": "navigator",
        "11": "gale",
        "12": "training",
        "13": "fire",
        "14": "minerals",
        "15": "carbon",
        "16": "water",
        "17": "agriculture",
        "18": "C",
        "19": "E",
        "20": "A",
        "21": "D",
        "22": "E",
        "23": "C",
        "24": "F",
        "25": "G",
        "26": "F",
        "27": "D",
        "28": "A",
        "29": "B",
        "30": "F",
        "31": "B",
        "32": "G",
        "33": "E",
        "34": "A",
        "35": "YES",
        "36": "NOT GIVEN",
        "37": "NO",
        "38": "NOT GIVEN",
        "39": "YES",
        "40": "NO",
    },
    "cambridge-14|test-1": {
        "1": "creativity",
        "2": "rules",
        "3": "cities",
        "4": "traffic",
        "5": "crime",
        "6": "competition",
        "7": "evidence",
        "8": "life",
        "9": "TRUE",
        "10": "TRUE",
        "11": "NOT GIVEN",
        "12": "FALSE",
        "13": "TRUE",
        "14": "E",
        "15": "C",
        "16": "F",
        "17": "C",
        "18": "A",
        "19": "B",
        "20": "D",
        "21": "D",
        "22": "E",
        "23": "activists",
        "24": "consumerism",
        "25": "leaflets",
        "26": "police",
        "27": "E",
        "28": "D",
        "29": "B",
        "30": "D",
        "31": "C",
        "32": "YES",
        "33": "NO",
        "34": "NO",
        "35": "NOT GIVEN",
        "36": "restaurants",
        "37": "performance",
        "38": "turnover",
        "39": "goals",
        "40": "characteristics",
    },
    "cambridge-14|test-2": {
        "1": "FALSE",
        "2": "TRUE",
        "3": "NOT GIVEN",
        "4": "FALSE",
        "5": "NOT GIVEN",
        "6": "TRUE",
        "7": "FALSE",
        "8": "TRUE",
        "9": "merchant",
        "10": "equipment",
        "11": "gifts",
        "12": "canoe",
        "13": "mountains",
        "14": "F",
        "15": "C",
        "16": "E",
        "17": "D",
        "18": "B",
        "19": "design(s)",
        "20": "pathogens",
        "21": "tuberculosis",
        "22": "wards",
        "23": "communal",
        "24": "public",
        "25": "miasmas",
        "26": "cholera",
        "27": "vi",
        "28": "i",
        "29": "iii",
        "30": "ii",
        "31": "ix",
        "32": "vii",
        "33": "iv",
        "34": "viii",
        "35": "productive",
        "36": "perfectionists",
        "37": "dissatisfied",
        "38": "TRUE",
        "39": "FALSE",
        "40": "NOT GIVEN",
    },
    "cambridge-14|test-3": {
        "1": "B",
        "2": "A",
        "3": "D",
        "4": "NOT GIVEN",
        "5": "NO",
        "6": "YES",
        "7": "B",
        "8": "C",
        "9": "B",
        "10": "A",
        "11": "A",
        "12": "C",
        "13": "A",
        "14": "C",
        "15": "H",
        "16": "A",
        "17": "F",
        "18": "I",
        "19": "B",
        "20": "E",
        "21": "B",
        "22": "C",
        "23": "ecology",
        "24": "prey",
        "25": "habitats",
        "26": "antibiotics",
        "27": "B",
        "28": "G",
        "29": "F",
        "30": "E",
        "31": "C",
        "32": "NO",
        "33": "YES",
        "34": "NOT GIVEN",
        "35": "NO",
        "36": "YES",
        "37": "encouraging",
        "38": "desire",
        "39": "autonomy",
        "40": "targeted",
    },
    "cambridge-14|test-4": {
        "1": ["four", "4"],
        "2": "young",
        "3": "food",
        "4": "light",
        "5": "aggressively",
        "6": "location",
        "7": "neurons",
        "8": "chemicals",
        "9": "FALSE",
        "10": "TRUE",
        "11": "FALSE",
        "12": "NOT GIVEN",
        "13": "TRUE",
        "14": "B",
        "15": "E",
        "16": "C",
        "17": "A",
        "18": "TRUE",
        "19": "TRUE",
        "20": "NOT GIVEN",
        "21": "FALSE",
        "22": "NOT GIVEN",
        "23": "B",
        "24": "D",
        "25": "B",
        "26": "E",
        "27": "FALSE",
        "28": "NOT GIVEN",
        "29": "FALSE",
        "30": "TRUE",
        "31": "FALSE",
        "32": "TRUE",
        "33": "NOT GIVEN",
        "34": "large",
        "35": "microplastic",
        "36": "populations",
        "37": "concentrations",
        "38": "predators",
        "39": "disasters",
        "40": "A",
    },
    "cambridge-15|test-1": {
        "1": "oval",
        "2": "husk",
        "3": "seed",
        "4": "mace",
        "5": "FALSE",
        "6": "NOT GIVEN",
        "7": "TRUE",
        "8": "Arabs",
        "9": "plague",
        "10": "lime",
        "11": "Run",
        "12": "Mauritius",
        "13": "tsunami",
        "14": "C",
        "15": "B",
        "16": "E",
        "17": "G",
        "18": "D",
        "19": "human error",
        "20": "car (-) sharing",
        "21": "ownership",
        "22": "mileage",
        "23": "C",
        "24": "D",
        "25": "A",
        "26": "E",
        "27": "A",
        "28": "C",
        "29": "C",
        "30": "D",
        "31": "A",
        "32": "B",
        "33": "E",
        "34": "A",
        "35": "D",
        "36": "E",
        "37": "B",
        "38": "(unique) expeditions",
        "39": ["uncontacted", "isolated"],
        "40": "(land) surface",
    },
    "cambridge-15|test-2": {
        "1": "B",
        "2": "C",
        "3": "F",
        "4": "D",
        "5": "E",
        "6": "A",
        "7": "safety",
        "8": "traffic",
        "9": "carriageway",
        "10": "mobile",
        "11": "dangerous",
        "12": "communities",
        "13": "healthy",
        "14": "F",
        "15": "A",
        "16": "D",
        "17": "A",
        "18": "genetic traits",
        "19": "heat loss",
        "20": "ears",
        "21": "(insulating) fat",
        "22": "(carbon) emissions",
        "23": "B",
        "24": "C",
        "25": "A",
        "26": "C",
        "27": "C",
        "28": "A",
        "29": "B",
        "30": "B",
        "31": "D",
        "32": "F",
        "33": "H",
        "34": "C",
        "35": "D",
        "36": "E",
        "37": "NOT GIVEN",
        "38": "YES",
        "39": "NO",
        "40": "NO",
    },
    "cambridge-15|test-3": {
        "1": "TRUE",
        "2": "FALSE",
        "3": "NOT GIVEN",
        "4": "TRUE",
        "5": "NOT GIVEN",
        "6": "FALSE",
        "7": "TRUE",
        "8": "resignation",
        "9": "materials",
        "10": "miners",
        "11": "family",
        "12": "collectors",
        "13": "income",
        "14": "iii",
        "15": "vi",
        "16": "v",
        "17": "x",
        "18": "iv",
        "19": "viii",
        "20": "i",
        "21": "wheels",
        "22": "film",
        "23": "filter",
        "24": "waste",
        "25": "performance",
        "26": "servicing",
        "27": "C",
        "28": "B",
        "29": "F",
        "30": "A",
        "31": "E",
        "32": "D",
        "33": "F",
        "34": "B",
        "35": "C",
        "36": "G",
        "37": "B",
        "38": "D",
        "39": "A",
        "40": "A",
    },
    "cambridge-15|test-4": {
        "1": "water",
        "2": "diet",
        "3": "drought",
        "4": "erosion",
        "5": "desert",
        "6": ["(its", "huarango", "the) branches"],
        "7": "IN EITHER ORDER (BOTH REQUIRED FOR ONE MARK) leaves (and) bark",
        "8": ["(its", "huarango", "the) trunk"],
        "9": "NOT GIVEN",
        "10": "FALSE",
        "11": "TRUE",
        "12": "FALSE",
        "13": "NOT GIVEN",
        "14": "NOT GIVEN",
        "15": "FALSE",
        "16": "TRUE",
        "17": "FALSE",
        "18": "FALSE",
        "19": "TRUE",
        "20": "words",
        "21": "finger",
        "22": "direction",
        "23": "commands",
        "24": "fires",
        "25": "technology",
        "26": "award",
        "27": "D",
        "28": "E",
        "29": "F",
        "30": "H",
        "31": "B",
        "32": "C",
        "33": "D",
        "34": "B",
        "35": "YES",
        "36": "NOT GIVEN",
        "37": "NO",
        "38": "YES",
        "39": "NOT GIVEN",
        "40": "D",
    },
    "cambridge-20|test-1": {
        "1": "FALSE",
        "2": "FALSE",
        "3": "FALSE",
        "4": "NOT GIVEN",
        "5": "TRUE",
        "6": "TRUE",
        "7": "bulbs",
        "8": "soil",
        "9": "feathers",
        "10": "deer",
        "11": "1980",
        "12": "funding",
        "13": "stakeholders",
        "14": "C",
        "15": "G",
        "16": "B",
        "17": "E",
        "18": "C",
        "19": "B",
        "20": "A",
        "21": "B",
        "22": "C",
        "23": "A",
        "24": "oak",
        "25": "flooring",
        "26": "keel",
        "27": "C",
        "28": "A",
        "29": "D",
        "30": "C",
        "31": "B",
        "32": "G",
        "33": "F",
        "34": "E",
        "35": "D",
        "36": "YES",
        "37": "NOT GIVEN",
        "38": "NO",
        "39": "YES",
        "40": "YES"
    },
    "cambridge-20|test-2": {
        "1": "tail",
        "2": "flippers",
        "3": "hair",
        "4": "seagrasses",
        "5": "lips",
        "6": "buoyancy",
        "7": "TRUE",
        "8": "NOT GIVEN",
        "9": "FALSE",
        "10": "NOT GIVEN",
        "11": "TRUE",
        "12": "NOT GIVEN",
        "13": "TRUE",
        "14": "B",
        "15": "F",
        "16": "B",
        "17": "laziness",
        "18": "anxious",
        "19": "threats",
        "20": "exams",
        "21": "perfectionists",
        "22": "guilt",
        "23": ["A", "C"],
        "24": ["A", "C"],
        "25": ["A", "E"],
        "26": ["A", "E"],
        "27": "NO",
        "28": "YES",
        "29": "NOT GIVEN",
        "30": "NO",
        "31": "NOT GIVEN",
        "32": "YES",
        "33": "F",
        "34": "D",
        "35": "H",
        "36": "B",
        "37": "G",
        "38": "B",
        "39": "D",
        "40": "C"
    },
    "cambridge-17|test-3": {
        "1": "carnivorous",
        "2": "scent",
        "3": "pouch",
        "4": "fossil",
        "5": "habitat",
        "6": "TRUE",
        "7": "FALSE",
        "8": "NOT GIVEN",
        "9": "FALSE",
        "10": "NOT GIVEN",
        "11": "FALSE",
        "12": "TRUE",
        "13": "FALSE",
        "14": "F",
        "15": "G",
        "16": "A",
        "17": "H",
        "18": "B",
        "19": "E",
        "20": "C",
        "21": "B",
        "22": "C",
        "23": "solid",
        "24": ["Sumatran orangutan", "orangutan"],
        "25": "carbon stocks",
        "26": "biodiversity",
        "27": "D",
        "28": "B",
        "29": "C",
        "30": "D",
        "31": "C",
        "32": "NO",
        "33": "YES",
        "34": "NO",
        "35": "NO",
        "36": "H",
        "37": "D",
        "38": "I",
        "39": "B",
        "40": "F"
    },
    "cambridge-20|test-3": {
        "1": "potatoes",
        "2": "butter",
        "3": "meat",
        "4": "crystals",
        "5": "cellophane",
        "6": "tin",
        "7": "refrigerator",
        "8": "NOT GIVEN",
        "9": "TRUE",
        "10": "FALSE",
        "11": "TRUE",
        "12": "FALSE",
        "13": "NOT GIVEN",
        "14": "v",
        "15": "ii",
        "16": "iv",
        "17": "vii",
        "18": "iii",
        "19": "vi",
        "20": ["C", "E"],
        "21": ["C", "E"],
        "22": ["B", "D"],
        "23": ["B", "D"],
        "24": "tentacles",
        "25": "protection",
        "26": "colour",
        "27": "A",
        "28": "C",
        "29": "B",
        "30": "A",
        "31": "B",
        "32": "A",
        "33": "C",
        "34": "C",
        "35": "B",
        "36": "D",
        "37": "B",
        "38": "C",
        "39": "B",
        "40": "C"
    },
    "cambridge-20|test-4": {
        "1": "teacher",
        "2": "charcoal",
        "3": "skyscrapers",
        "4": "flowers",
        "5": "bones",
        "6": "landscape",
        "7": "rivers",
        "8": "FALSE",
        "9": "TRUE",
        "10": "FALSE",
        "11": "TRUE",
        "12": "NOT GIVEN",
        "13": "FALSE",
        "14": "C",
        "15": "A",
        "16": "D",
        "17": "F",
        "18": "pumps",
        "19": "dams",
        "20": "float",
        "21": "crops",
        "22": "trees",
        "23": "B",
        "24": "E",
        "25": "A",
        "26": "C",
        "27": "D",
        "28": "G",
        "29": "B",
        "30": "C",
        "31": "B",
        "32": "D",
        "33": "E",
        "34": "B",
        "35": "C",
        "36": "A",
        "37": "jackals",
        "38": "diseases",
        "39": "food",
        "40": "foxes"
    }
};
